name: arre_assignmemnt
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^9.2.0
  dio: ^5.5.0+1
  dio_smart_retry: ^6.0.0
  duration: ^3.0.13
  flash: ^3.1.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  hive_ce_flutter: ^2.0.0
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  platform_info: ^4.0.2
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  talker_dio_logger: ^4.4.0
  talker_flutter: ^4.4.0
  talker_riverpod_logger: ^4.4.0
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.3.12
  riverpod_test: ^0.1.6
  very_good_analysis: ^6.0.0


 # Added for support WASM
dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    # Apply transformer to a single SVG file
    - path: assets/svg/